{{- $ns := lookup "v1" "Namespace" "" "akuity" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
data:
  instance: {{ $ns.metadata.labels "akuity.io/argo-cd-instance-id" | default "unknown" }}
