apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-helm-lookup
  namespace: argocd
spec:
  destination:
    namespace: guestbook-helmlookup
    name: temp
  source:
    path: us
    repoURL: https://github.com/34fathombelow/argocd-example-apps.git
    targetRevision: testing
    plugin:
      name: helm-lookup
      parameters:
        - array:
            - stage.yaml
          name: values-files
        - map:
            replicaCount: 2
          name: helm-parameters
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
