apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-helm-lookup
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: guestbook-helmlookup
    name: temp
  source:
    path: us
    repoURL: https://github.com/34fathombelow/argocd-example-apps.git
    targetRevision: testing
    plugin:
      name: helm-lookup
      parameters:
        - array:
            - values-production.yaml
          name: values-files
      env:
        - name: HELM_VALUES_FILE
          value: stage.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
